/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeeCollectionRouteImport } from './routes/fee-collection'
import { Route as PaymentHistoryRouteImport } from './routes/payment-history'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudentsRouteImport } from './routes/students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeCollectionRoute = FeeCollectionRouteImport.update({
  id: '/fee-collection',
  path: '/fee-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentHistoryRoute = PaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fee-collection': typeof FeeCollectionRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/receipts': typeof ReceiptsRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fee-collection': typeof FeeCollectionRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/receipts': typeof ReceiptsRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fee-collection': typeof FeeCollectionRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/receipts': typeof ReceiptsRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/fee-collection'
    | '/payment-history'
    | '/receipts'
    | '/reminders'
    | '/settings'
    | '/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/fee-collection'
    | '/payment-history'
    | '/receipts'
    | '/reminders'
    | '/settings'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/fee-collection'
    | '/payment-history'
    | '/receipts'
    | '/reminders'
    | '/settings'
    | '/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FeeCollectionRoute: typeof FeeCollectionRoute
  PaymentHistoryRoute: typeof PaymentHistoryRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RemindersRoute: typeof RemindersRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-collection': {
      id: '/fee-collection'
      path: '/fee-collection'
      fullPath: '/fee-collection'
      preLoaderRoute: typeof FeeCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-history': {
      id: '/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof PaymentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FeeCollectionRoute: FeeCollectionRoute,
  PaymentHistoryRoute: PaymentHistoryRoute,
  ReceiptsRoute: ReceiptsRoute,
  RemindersRoute: RemindersRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
